name: managua
favicon: null
layout_spectrum: 0.75529
typography_spectrum: 0
title: managua
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#584a3b'
    - '#abae95'
    - '#b6443b'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
