name: managua
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.24058
title: managua life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#584a3b'
    - '#abae95'
    - '#b6443b'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
