name: managua
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: managua
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecedf1'
    - '#181310'
    - '#b7b9c5'
    - '#313234'
    - '#808186'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
