name: managua
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44282
title: managua
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#49bfd9'
    - '#ece0b8'
    - '#b5b7b2'
    - '#4a3b24'
    - '#998e3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
