name: managua
favicon: null
layout_spectrum: 0.51906
typography_spectrum: 0.76116
title: managua
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d8db'
    - '#0a0c13'
    - '#6e8fba'
    - '#4b5455'
    - '#880e13'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
